version: '3.0'

networks:
    backend:
        name: 'sc'

services:
    wordpress:
        networks:
            - 'backend'
        image: wordpress:latest
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_USER: uczestnik
            WORDPRESS_DB_PASSWORD: zaq1@WSX
            WORDPRESS_DB_NAME: baza
            WORDPRESS_DB_HOST: db:3306

volumes:
    db_data: {}
            
