version: '3.0'

networks:
    backend:
        name: 'sc'

services:
    db:
        image: mysql:5.7
        volumes: 
            - db_data:/var/lib/mysql
        restart: always
        networks:
            - 'backend'
        environment:
            MYSQL_ROOT_PASSWORD: zaq1@WSX
            MYSQL_USER: uczestnik
            MYSQL_DATABASE: baza
            MYSQL_PASSWORD: zaq1@WSX

volumes:
    db_data: {}
